---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mypkg
```{r proposal}
#this is a usuless proposal
```

<!-- badges: start -->
<!-- badges: end -->

The goal of `mypkg` is to learn how to create a package and how to use GitHub.

<<<<<<< HEAD
I want to create a conflict because I like arguing...
=======
I am making some changes in mu pkg.
>>>>>>> 1bb9e4135e1f13faff97aec772ea0b7b27868947

## Installation

You can install the released version of mypkg_Iris from [CRAN](https://CRAN.R-project.org) with:

``` r

```
```{r}
#install.packages("mypkg")
```

And the development version from [GitHub](https://github.com/) with:

``` r

```
## Example
```{r}
# install.packages("devtools")
devtools::install_github("IrisGanser/mypkg_Iris")
```

This is a basic example which shows you how to use the function `mylog` in `mypkg`:

```{r example}
library(mypkg)
x <- 1:10
mypkg::mylog(x)
```

